# Generated by Django 5.0.1 on 2024-01-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BCentri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=40)),
                ('materiales_carcaza', models.CharField(max_length=40)),
                ('materiales_voluta', models.CharField(max_length=40)),
                ('presion', models.FloatField()),
                ('caudal', models.FloatField()),
                ('altura', models.FloatField()),
                ('temp', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Bengranajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=40)),
                ('materiales_carcaza', models.CharField(max_length=40)),
                ('meteriales_engranajes', models.CharField(max_length=40)),
                ('presion', models.FloatField()),
                ('caudal', models.FloatField()),
                ('altura', models.FloatField()),
                ('temp', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Btornillo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=40)),
                ('materiales_carcaza', models.CharField(max_length=40)),
                ('meteriales_tornillo', models.CharField(max_length=40)),
                ('presion', models.FloatField()),
                ('caudal', models.FloatField()),
                ('altura', models.FloatField()),
                ('temp', models.FloatField()),
            ],
        ),
    ]
