# Generated by Django 5.0.1 on 2024-01-19 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appentrega', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bengranajes',
            old_name='meteriales_engranajes',
            new_name='materiales_engranajes',
        ),
        migrations.RenameField(
            model_name='btornillo',
            old_name='meteriales_tornillo',
            new_name='materiales_tornillo',
        ),
    ]
